// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_fully_dedicated = "CgkIyrH_s44YEAIQBA"; // <GPGSID>
        public const string achievement_hardworker = "CgkIyrH_s44YEAIQAg"; // <GPGSID>
        public const string achievement_you_received_10_godly_fingers = "CgkIyrH_s44YEAIQAw"; // <GPGSID>
        public const string achievement_new_car_sassy = "CgkIyrH_s44YEAIQCg"; // <GPGSID>
        public const string achievement_master_sooo_great = "CgkIyrH_s44YEAIQDA"; // <GPGSID>
        public const string achievement_you_received_20_godly_fingers = "CgkIyrH_s44YEAIQCA"; // <GPGSID>
        public const string leaderboard_global_ranking = "CgkIyrH_s44YEAIQDg"; // <GPGSID>
        public const string achievement_new_ride_marvellous = "CgkIyrH_s44YEAIQCQ"; // <GPGSID>
        public const string achievement_born_to_be_the_best = "CgkIyrH_s44YEAIQBg"; // <GPGSID>
        public const string achievement_new_car_yay = "CgkIyrH_s44YEAIQBw"; // <GPGSID>
        public const string achievement_you_unlocked_the_car = "CgkIyrH_s44YEAIQDQ"; // <GPGSID>
        public const string achievement_new_car_unlocked = "CgkIyrH_s44YEAIQBQ"; // <GPGSID>
        public const string achievement_you_received_5_godly_fingers = "CgkIyrH_s44YEAIQAQ"; // <GPGSID>
        public const string achievement_fastest_dialler_aspirant = "CgkIyrH_s44YEAIQAA"; // <GPGSID>
        public const string achievement_new_ride_so_classy = "CgkIyrH_s44YEAIQCw"; // <GPGSID>

}

